2021-02-08T16:13:08,760 Using pip 20.2.4 from /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pip (python 3.8)
2021-02-08T16:13:08,762 Non-user install because site-packages writeable
2021-02-08T16:13:08,780 Created temporary directory: /private/var/folders/sx/08ffxgcs4qv542km9gw0h08c0000gp/T/pip-ephem-wheel-cache-cjvy12zi
2021-02-08T16:13:08,781 Created temporary directory: /private/var/folders/sx/08ffxgcs4qv542km9gw0h08c0000gp/T/pip-req-tracker-g6hbetcs
2021-02-08T16:13:08,781 Initialized build tracking at /private/var/folders/sx/08ffxgcs4qv542km9gw0h08c0000gp/T/pip-req-tracker-g6hbetcs
2021-02-08T16:13:08,781 Created build tracker: /private/var/folders/sx/08ffxgcs4qv542km9gw0h08c0000gp/T/pip-req-tracker-g6hbetcs
2021-02-08T16:13:08,781 Entered build tracker: /private/var/folders/sx/08ffxgcs4qv542km9gw0h08c0000gp/T/pip-req-tracker-g6hbetcs
2021-02-08T16:13:08,782 Created temporary directory: /private/var/folders/sx/08ffxgcs4qv542km9gw0h08c0000gp/T/pip-install-opeuwy4y
2021-02-08T16:13:08,785 Collecting git+ssh://****@github.com:/Patreon/frud-service.git@f478bbb361cf4fcb1d244e8f7ec8852a1c951f42#subdirectory=client_package
2021-02-08T16:13:08,785   Created temporary directory: /private/var/folders/sx/08ffxgcs4qv542km9gw0h08c0000gp/T/pip-req-build-b_cctsvt
2021-02-08T16:13:08,786   Cloning ssh://****@github.com:/Patreon/frud-service.git (to revision f478bbb361cf4fcb1d244e8f7ec8852a1c951f42) to /private/var/folders/sx/08ffxgcs4qv542km9gw0h08c0000gp/T/pip-req-build-b_cctsvt
2021-02-08T16:13:08,813 ERROR: Command errored out with exit status 128: git clone -q 'ssh://****@github.com:/Patreon/frud-service.git' /private/var/folders/sx/08ffxgcs4qv542km9gw0h08c0000gp/T/pip-req-build-b_cctsvt Check the logs for full command output.
2021-02-08T16:13:08,814 Exception information:
2021-02-08T16:13:08,814 Traceback (most recent call last):
2021-02-08T16:13:08,814   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pip/_internal/cli/base_command.py", line 228, in _main
2021-02-08T16:13:08,814     status = self.run(options, args)
2021-02-08T16:13:08,814   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pip/_internal/cli/req_command.py", line 182, in wrapper
2021-02-08T16:13:08,814     return func(self, options, args)
2021-02-08T16:13:08,814   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pip/_internal/commands/install.py", line 323, in run
2021-02-08T16:13:08,814     requirement_set = resolver.resolve(
2021-02-08T16:13:08,814   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pip/_internal/resolution/legacy/resolver.py", line 183, in resolve
2021-02-08T16:13:08,814     discovered_reqs.extend(self._resolve_one(requirement_set, req))
2021-02-08T16:13:08,814   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pip/_internal/resolution/legacy/resolver.py", line 388, in _resolve_one
2021-02-08T16:13:08,814     abstract_dist = self._get_abstract_dist_for(req_to_install)
2021-02-08T16:13:08,814   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pip/_internal/resolution/legacy/resolver.py", line 340, in _get_abstract_dist_for
2021-02-08T16:13:08,814     abstract_dist = self.preparer.prepare_linked_requirement(req)
2021-02-08T16:13:08,814   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pip/_internal/operations/prepare.py", line 467, in prepare_linked_requirement
2021-02-08T16:13:08,814     local_file = unpack_url(
2021-02-08T16:13:08,814   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pip/_internal/operations/prepare.py", line 239, in unpack_url
2021-02-08T16:13:08,814     unpack_vcs_link(link, location)
2021-02-08T16:13:08,814   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pip/_internal/operations/prepare.py", line 99, in unpack_vcs_link
2021-02-08T16:13:08,814     vcs_backend.unpack(location, url=hide_url(link.url))
2021-02-08T16:13:08,814   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pip/_internal/vcs/versioncontrol.py", line 733, in unpack
2021-02-08T16:13:08,814     self.obtain(location, url=url)
2021-02-08T16:13:08,814   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pip/_internal/vcs/versioncontrol.py", line 641, in obtain
2021-02-08T16:13:08,814     self.fetch_new(dest, url, rev_options)
2021-02-08T16:13:08,814   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pip/_internal/vcs/git.py", line 230, in fetch_new
2021-02-08T16:13:08,814     self.run_command(make_command('clone', '-q', url, dest))
2021-02-08T16:13:08,814   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pip/_internal/vcs/versioncontrol.py", line 771, in run_command
2021-02-08T16:13:08,814     return call_subprocess(cmd, cwd,
2021-02-08T16:13:08,814   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pip/_internal/vcs/versioncontrol.py", line 166, in call_subprocess
2021-02-08T16:13:08,814     raise SubProcessError(exc_msg)
2021-02-08T16:13:08,814 pip._internal.exceptions.SubProcessError: Command errored out with exit status 128: git clone -q 'ssh://****@github.com:/Patreon/frud-service.git' /private/var/folders/sx/08ffxgcs4qv542km9gw0h08c0000gp/T/pip-req-build-b_cctsvt Check the logs for full command output.
2021-02-08T16:13:08,857 WARNING: You are using pip version 20.2.4; however, version 21.0.1 is available.
2021-02-08T16:13:08,857 You should consider upgrading via the '/Library/Frameworks/Python.framework/Versions/3.8/bin/python3.8 -m pip install --upgrade pip' command.
2021-02-08T16:13:08,857 Removed build tracker: '/private/var/folders/sx/08ffxgcs4qv542km9gw0h08c0000gp/T/pip-req-tracker-g6hbetcs'
2021-02-08T16:16:56,002 Using pip 20.2.4 from /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pip (python 3.8)
2021-02-08T16:16:56,004 Non-user install because site-packages writeable
2021-02-08T16:16:56,023 Created temporary directory: /private/var/folders/sx/08ffxgcs4qv542km9gw0h08c0000gp/T/pip-ephem-wheel-cache-t7ly3ajh
2021-02-08T16:16:56,024 Created temporary directory: /private/var/folders/sx/08ffxgcs4qv542km9gw0h08c0000gp/T/pip-req-tracker-53d0th72
2021-02-08T16:16:56,024 Initialized build tracking at /private/var/folders/sx/08ffxgcs4qv542km9gw0h08c0000gp/T/pip-req-tracker-53d0th72
2021-02-08T16:16:56,024 Created build tracker: /private/var/folders/sx/08ffxgcs4qv542km9gw0h08c0000gp/T/pip-req-tracker-53d0th72
2021-02-08T16:16:56,024 Entered build tracker: /private/var/folders/sx/08ffxgcs4qv542km9gw0h08c0000gp/T/pip-req-tracker-53d0th72
2021-02-08T16:16:56,024 Created temporary directory: /private/var/folders/sx/08ffxgcs4qv542km9gw0h08c0000gp/T/pip-install-x5bv_uh_
2021-02-08T16:16:56,028 Collecting git+ssh://****@github.com/Patreon/frud-service.git@f478bbb361cf4fcb1d244e8f7ec8852a1c951f42#subdirectory=client_package
2021-02-08T16:16:56,028   Created temporary directory: /private/var/folders/sx/08ffxgcs4qv542km9gw0h08c0000gp/T/pip-req-build-t_c0j7u1
2021-02-08T16:16:56,029   Cloning ssh://****@github.com/Patreon/frud-service.git (to revision f478bbb361cf4fcb1d244e8f7ec8852a1c951f42) to /private/var/folders/sx/08ffxgcs4qv542km9gw0h08c0000gp/T/pip-req-build-t_c0j7u1
2021-02-08T16:16:56,069 ERROR: Command errored out with exit status 128: git clone -q 'ssh://****@github.com/Patreon/frud-service.git' /private/var/folders/sx/08ffxgcs4qv542km9gw0h08c0000gp/T/pip-req-build-t_c0j7u1 Check the logs for full command output.
2021-02-08T16:16:56,070 Exception information:
2021-02-08T16:16:56,070 Traceback (most recent call last):
2021-02-08T16:16:56,070   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pip/_internal/cli/base_command.py", line 228, in _main
2021-02-08T16:16:56,070     status = self.run(options, args)
2021-02-08T16:16:56,070   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pip/_internal/cli/req_command.py", line 182, in wrapper
2021-02-08T16:16:56,070     return func(self, options, args)
2021-02-08T16:16:56,070   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pip/_internal/commands/install.py", line 323, in run
2021-02-08T16:16:56,070     requirement_set = resolver.resolve(
2021-02-08T16:16:56,070   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pip/_internal/resolution/legacy/resolver.py", line 183, in resolve
2021-02-08T16:16:56,070     discovered_reqs.extend(self._resolve_one(requirement_set, req))
2021-02-08T16:16:56,070   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pip/_internal/resolution/legacy/resolver.py", line 388, in _resolve_one
2021-02-08T16:16:56,070     abstract_dist = self._get_abstract_dist_for(req_to_install)
2021-02-08T16:16:56,070   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pip/_internal/resolution/legacy/resolver.py", line 340, in _get_abstract_dist_for
2021-02-08T16:16:56,070     abstract_dist = self.preparer.prepare_linked_requirement(req)
2021-02-08T16:16:56,070   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pip/_internal/operations/prepare.py", line 467, in prepare_linked_requirement
2021-02-08T16:16:56,070     local_file = unpack_url(
2021-02-08T16:16:56,070   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pip/_internal/operations/prepare.py", line 239, in unpack_url
2021-02-08T16:16:56,070     unpack_vcs_link(link, location)
2021-02-08T16:16:56,070   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pip/_internal/operations/prepare.py", line 99, in unpack_vcs_link
2021-02-08T16:16:56,070     vcs_backend.unpack(location, url=hide_url(link.url))
2021-02-08T16:16:56,070   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pip/_internal/vcs/versioncontrol.py", line 733, in unpack
2021-02-08T16:16:56,070     self.obtain(location, url=url)
2021-02-08T16:16:56,070   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pip/_internal/vcs/versioncontrol.py", line 641, in obtain
2021-02-08T16:16:56,070     self.fetch_new(dest, url, rev_options)
2021-02-08T16:16:56,070   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pip/_internal/vcs/git.py", line 230, in fetch_new
2021-02-08T16:16:56,070     self.run_command(make_command('clone', '-q', url, dest))
2021-02-08T16:16:56,070   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pip/_internal/vcs/versioncontrol.py", line 771, in run_command
2021-02-08T16:16:56,070     return call_subprocess(cmd, cwd,
2021-02-08T16:16:56,070   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pip/_internal/vcs/versioncontrol.py", line 166, in call_subprocess
2021-02-08T16:16:56,070     raise SubProcessError(exc_msg)
2021-02-08T16:16:56,070 pip._internal.exceptions.SubProcessError: Command errored out with exit status 128: git clone -q 'ssh://****@github.com/Patreon/frud-service.git' /private/var/folders/sx/08ffxgcs4qv542km9gw0h08c0000gp/T/pip-req-build-t_c0j7u1 Check the logs for full command output.
2021-02-08T16:16:56,120 WARNING: You are using pip version 20.2.4; however, version 21.0.1 is available.
2021-02-08T16:16:56,120 You should consider upgrading via the '/Library/Frameworks/Python.framework/Versions/3.8/bin/python3.8 -m pip install --upgrade pip' command.
2021-02-08T16:16:56,121 Removed build tracker: '/private/var/folders/sx/08ffxgcs4qv542km9gw0h08c0000gp/T/pip-req-tracker-53d0th72'
